### ISSUE TITLE
Attribute type, unit, precision, not copied correctly by the Copy transformer

### ISSUE THREAD

**Issue by stardust66** [P-bibs/CODAP-flow#109]
To reproduce, take the NOAA Weather dataset and copy it. Notice all the units in the attribute names are gone in the copy, and if you open the attribute info panel, the precision and type information are gone as well.

**Comment by thomascastleman** [comment]
This is arguably an error on the part of the NOAA dataset, which doesn't seem to be marking some of its numeric attributes as numeric. The attribute type does seem to be getting copied over (check out the `when` attribute). We only copy the `precision` and `unit`, however, if the type is numeric (see below), but most of their attributes seem to be blank.

https://github.com/P-bibs/CODAP-flow/blob/4cc6f88ec2ce19a223a9a9ddd17ccc87fba2c8a6/src/utils/codapPhone/index.ts#L417-L418

It is dissatisfying though that it fails to accommodate the lack of type in the NOAA dataset and doesn't just copy anyway. I think the reason we're checking is for type safety. Maybe we want to do something less safe with casts to make sure they are always copied?

**Comment by stardust66** [comment]
Ah, I didn't think it was possible for the type to be empty but for units to be respected by CODAP. I'll probably just modify the type to be looser to accommodate all these cases and then we can just copy everything.
