### ISSUE TITLE
Listener that depends on two input datasets doesn't get deleted when one of the inputs is deleted

### ISSUE THREAD

**Issue by stardust66** [P-bibs/CODAP-flow#131]
For example, start comparing two columns from two different datasets. Then, delete one of them. Now, edit the other input dataset so the compare updates. You can see that the updates still goes through (but it does not error since it uses the cached value of the deleted input dataset, which is a separate issue).

**Comment by thomascastleman** [comment]
Good catch. This seems to be because the dependencies for compare aren't probably expressed. At the moment, we add two update listeners for the input datasets, and each depends only on the output dataset. In reality, they should each depend on the output dataset _and_ the other input.
