### ISSUE TITLE
"Invalid attribute" when attribute is valid

### ISSUE THREAD

**Issue by thomascastleman** [P-bibs/CODAP-flow#148]
1. Create a dataset with two collections (e.g. Microdata)
2. Transform this dataset with something that uses an attribute _in the child collection_ (e.g. Transform Column)
3. Delete all cases in the input dataset (this update should flow to the output--all good)
4. Start defining a case in the input by defining something in the parent collection

Now you should get an error during the update, indicating that the attribute (from the child collection) is invalid, even though it clearly is valid. This is what Paul mentioned in #144 -- cases can be `undefined` for a given attribute in weird circumstances and this is one of them.

This raises the question of what we want to do in this case: Raise a different error? On the other hand we might want to make these `undefined` values behave like missing values (that's what they look like to the user, after all), in which a case the Transform Column would go through correctly.

Thoughts? @stardust66 @P-bibs

**Comment by P-bibs** [comment]
I'm partial to the treating them like missing values approach, since having two values that look the same to the user (empty string and `undefined`) but behave different seems like it could lead to frustrating behavior.

**Comment by thomascastleman** [comment]
Since #151, we no longer get an "Invalid attribute" error when the attribute is valid (we've switched to treating those `undefined`s as missing values. So I think it's fair to close this. 

But worth noting that the example given above still errors but now from the CODAP end--we send records with `undefined`, so it considers the attribute "unrecognized". This is arguably a CODAP bug, since `undefined` _appears_ graphically as a missing value, so it should either be treated as such or just not represented using `undefined`.

Good to close? @stardust66 @P-bibs
