### ISSUE TITLE
deleted table used in transformer after deletion

### ISSUE THREAD

**Issue by thomascastleman** [P-bibs/CODAP-flow#169]
To reproduce:

1. Transform the People dataset
2. Delete the People dataset
3. Hit "Apply Transformer" again without changing anything (the dropdown should be selecting one of the output tables of the previous transform)

Notice the transform applies to the People dataset, though it has been deleted and was not what was visible in the dropdown.

**Comment by thomascastleman** [comment]
Related to #132?

**Comment by thomascastleman** [comment]
FWIW, this happens with or without the updating of data context titles to add "[fixed]".

The transformation is going through because deleted data contexts are still cached but I don't think this is the root of the issue here--we shouldn't be accessing a deleted data context at all. When I use Copy as an example and log what the `contextName` is that it's receiving as input, it is `US Microdata` in step 3 of the above process, which is incorrect.

**Comment by thomascastleman** [comment]
Okay. I checked and `useDataContexts` seems to be doing its job properly. The context selector also looks like it updates (you don't see the deleted context as an option, and indeed it's not in the list anymore). However, at the level of `DataDrivenTransformer`, `state["context1"]` still is set to the previous value (ie "US Microdata"). 

The issue seems to be that this `onChange` isn't getting called when the context is deleted. If it were, presumably `state["context1"]` would be updated to some other context in the dropdown.

https://github.com/P-bibs/CODAP-flow/blob/d60346102dc90bad7528b09b55e0f9cfdd06c5ab/src/transformer-components/DataDrivenTransformer.tsx#L388-L394

I'm not sure why this isn't getting called. @stardust66 @P-bibs ?

**Comment by thomascastleman** [comment]
Okay I think this is because when data contexts are deleted, the `options` of the `select` change and it is re-rendered, but this doesn't trigger `onChange` being called--which I guess only happens when the `value` of the select changes.

Ideas on working around this?

**Comment by stardust66** [comment]
I have some ideas. I'll take a look.
