### ISSUE TITLE
plugin crashes when not embedded in CODAP

### ISSUE THREAD

**Issue by thomascastleman** [P-bibs/CODAP-flow#99]

**Comment by thomascastleman** [comment]
My approach was going to be to wrap the calls to `initPhone` below in a `try`/`catch` and render some kind of error if it fails, but this seems tricky because `initPhone` is asynchronous and I'm not sure how to make the `App` component async or if that's even the best solution here.

https://github.com/P-bibs/CODAP-flow/blob/0a84be141ad4ef65c48326deb331ea42e62adb6c/src/App.tsx#L7-L24

Thoughts? @P-bibs @stardust66

**Comment by stardust66** [comment]
Since async/await is just sugar around promises, you could also do `initPhone(...).catch(err => ...)`, and maybe set state there that triggers an error display?
